# Generated by Django 5.2.7 on 2025-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the sweet.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CHOCOLATE", "Chocolate"),
                            ("GUMMY", "Gummy"),
                            ("HARD_CANDY", "Hard Candy"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price of the sweet.", max_digits=5
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantity in stock."
                    ),
                ),
                (
                    "stock_level",
                    models.IntegerField(
                        default=0, help_text="Current stock level for the sweet."
                    ),
                ),
                ("is_available", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
