# Generated by Django 5.2.7 on 2025-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sweet",
            name="is_available",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
